Base image
nest/nest-docker pull request #80
Opened 2021-12-13 08:07 UTC by babsey

This PR adds Dockerfiles for two base-images for build and deployment stages.

2021-12-13 14:20 UTC, steffengraber commented on src/3.x/Dockerfile
> +    SRC_PATH=/tmp/nest-simulator
There should be `ARG ` in front of the argument.

2021-12-13 15:02 UTC, steffengraber requested changes
After all the deploy image started with "nest-server" raised the `error: /usr/local/bin/entrypoint.sh: line 38: exec: uwsgi: not found`

2021-12-14 07:38 UTC, steffengraber commented
The messoge now:

    tar: /tmp/nest-simulator-3.1: Cannot open: No such file or directory
    tar: Error is not recoverable: exiting now

I think to prepare NEST 3.2 it would be better to start from the dev version and not v3.1. What do you think?

2021-12-14 08:53 UTC, terhorstd commented
> I think to prepare NEST 3.2 it would be better to start from the dev version and not v3.1. What do you think?

The images should both (all) be built, since both have a different purpose. The releases have to trigger a build, obviously, but also the intermediate versions should be available to developers. The intermediate images need not be retained long term.

2021-12-14 08:59 UTC, babsey commented
It is the first draft to built it on GitLab CI and deploy on docker-registry.ebrains.

Since there is no release of v3.2 existed, I took v3.1 as example for Dockerfiles templates. 
Sure you can change it.

2021-12-14 09:07 UTC, steffengraber commented
I would see the goal of this PR as how the separation of the current image into build and deploy can work. The development of the right CI can be done in another PR.

2021-12-14 09:48 UTC, steffengraber approved these changes
Very good! Thank you.

2021-12-14 09:51 UTC, merged